title: NXUS COMIC
description: Diario de desarrollo del c√≥mic.
url: "https://nxuscomics.github.io" 
baseurl: "" 
markdown: kramdown
permalink: /:title/
gems: 
  - jekyll-feed
  
# Excluye archivos que no deben copiarse
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md